marketjs/market/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'panel/', 
        views.PanelHomeView.as_view(),
        name='index',
    ),
    path(
        'panel/admin/', 
        views.PanelAdminView.as_view(),
        name='index-admin',
    ),
    path(
        'panel/admin-reporte/', 
        views.ReporteAdmin.as_view(),
        name='admin-reporte',
    ),
    path(
        'panel/admin-liquidacion/', 
        views.ReporteLiquidacion.as_view(),
        name='admin-liquidacion',
    ),
    path(
        'panel/admin-resumen-ventas/', 
        views.ReporteResumenVentas.as_view(),
        name='admin-resumen_ventas',
    ),
]

marketjs/market/market/urls.py
"""
Proyecto Final
"""
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    # users app
    re_path('', include('applications.users.urls')),
    # producto app
    re_path('', include('applications.producto.urls')),
    # venta app
    re_path('', include('applications.venta.urls')),
    # caja app
    re_path('', include('applications.caja.urls')),
]

marketjs/market/applications/home/models.py
from django.db import models

# Create your models here.

marketjs/market/applications/venta/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete, post_save
#
from model_utils.models import TimeStampedModel

# local apps
from applications.producto.models import Product

#
from .managers import SaleManager, SaleDetailManager, CarShopManager
from .signals import update_stok_ventas_producto


class Sale(TimeStampedModel):
    """Modelo que representa a una Venta Global"""

    # tipo recibo constantes
    BOLETA = '0'
    FACTURA = '1'
    SIN_COMPROBANTE = '2'
    # tipo pago constantes
    TARJETA = '0'
    CASH = '1'
    BONO = '2'
    OTRO = '3'
    #
    TIPO_INVOCE_CHOICES = [
        (BOLETA, 'Boleta'),
        (FACTURA, 'Factura'),
        (SIN_COMPROBANTE, 'Sin Comprobante'),
    ]

    TIPO_PAYMENT_CHOICES = [
        (TARJETA, 'Tarjeta'),
        (CASH, 'Cash'),
        (BONO, 'Bono'),
        (OTRO, 'Otro'),
    ]

    date_sale = models.DateTimeField(
        'Fecha de Venta',
    )
    count = models.PositiveIntegerField('Cantidad de Productos')
    amount = models.DecimalField(
        'Monto', 
        max_digits=10, 
        decimal_places=2
    )
    type_invoce = models.CharField(
        'TIPO',
        max_length=2,
        choices=TIPO_INVOCE_CHOICES
    )
    type_payment = models.CharField(
        'TIPO PAGO',
        max_length=2,
        choices=TIPO_PAYMENT_CHOICES
    )
    close = models.BooleanField(
        'Venta cerrada',
        default=False
    )
    anulate = models.BooleanField(
        'Venta Anulada',
        default=False,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='cajero',
        related_name="user_venta",
    )

    objects = SaleManager()

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'ventas'

    def __str__(self):
        return 'Nº [' + str(self.id) + '] - ' + str(self.date_sale)



class SaleDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_sale'
    )
    sale = models.ForeignKey(
        Sale,
        on_delete=models.CASCADE, 
        verbose_name='Codigo de Venta',
        related_name='detail_sale'
    )
    count = models.PositiveIntegerField('Cantidad')
    price_purchase = models.DecimalField(
        'Precio Compra', 
        max_digits=10, 
        decimal_places=3
    )
    price_sale = models.DecimalField(
        'Precio Venta', 
        max_digits=10, 
        decimal_places=2
    )
    tax = models.DecimalField(
        'Impuesto', 
        max_digits=5,
        decimal_places=2
    )
    anulate = models.BooleanField(default=False)
    #

    objects = SaleDetailManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.name)


class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""

    barcode = models.CharField(
        max_length=13,
        unique=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_car'
    )
    count = models.PositiveIntegerField('Cantidad')
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.name)


# signals for venta
post_save.connect(update_stok_ventas_producto, sender=SaleDetail)

marketjs/market/applications/home/forms.py
from django import forms

from applications.producto.models import Provider


class LiquidacionProviderForm(forms.Form):

    provider = forms.ModelChoiceField(
        required=True,
        queryset=Provider.objects.all(),
        widget=forms.Select(
            attrs = {
                'class': 'input-group-field',
            }
        )
    )
    date_start = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'input-group-field',
            },
        )
    )
    date_end = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'input-group-field',
            },
        )
    )


class ResumenVentasForm(forms.Form):
    
    date_start = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'input-group-field',
            },
        )
    )
    date_end = forms.DateField(
        required=True,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'input-group-field',
            },
        )
    )

marketjs/market/applications/home/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView
)
from applications.venta.models import Sale, SaleDetail
from applications.producto.models import Product
from applications.users.mixins import AdminPermisoMixin
#
from .forms import LiquidacionProviderForm, ResumenVentasForm
#
from .functions import detalle_resumen_ventas


class PanelHomeView(TemplateView):
    template_name = "home/index.html"


class PanelAdminView(AdminPermisoMixin, TemplateView):
    template_name = "home/administrador.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_ventas"] = Sale.objects.total_ventas_dia()
        context["total_anulaciones"] = Sale.objects.total_ventas_anuladas_dia()
        context["stok_cero"] = Product.objects.productos_en_cero().count()
        context["resumen_semana"] = SaleDetail.objects.resumen_ventas()[:7]
        return context
    

class ReporteAdmin(AdminPermisoMixin, ListView):
    template_name = "home/reporte_admin.html"
    context_object_name = "resumen_ventas_mes"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_ventas"] = Sale.objects.total_ventas()
        return context
    
    def get_queryset(self):
        return SaleDetail.objects.resumen_ventas_mes()
    


class ReporteLiquidacion(AdminPermisoMixin, ListView):
    template_name = "home/reporte_liquidacion.html"
    context_object_name = "ventas_liquidacion"
    extra_context = {'form': LiquidacionProviderForm}
    
    def get_queryset(self):
        
        lista_ventas, total_ventas = SaleDetail.objects.resumen_ventas_proveedor(
            provider=self.request.GET.get("provider", ''),
            date_start=self.request.GET.get("date_start", ''),
            date_end=self.request.GET.get("date_end", ''),
        )
        self.extra_context.update({'total_ventas': total_ventas})
        return lista_ventas


class ReporteResumenVentas(AdminPermisoMixin, ListView):
    template_name = "home/resumen_ventas.html"
    context_object_name = "resumen_ventas"
    extra_context = {'form': ResumenVentasForm}
    
    def get_queryset(self):
        
        lista_ventas = detalle_resumen_ventas(
            self.request.GET.get("date_start", ''),
            self.request.GET.get("date_end", ''),
        )
        return lista_ventas

marketjs/market/templates/home/administrador.html
{% extends "home/base_home.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  
  <div class="cell grid-x grid-margin-x">
    <div class="cell medium-4 callout success" style="text-align: center;">
      <h5>Total Ventas Hoy</h5>
      <h3>S/ {{ total_ventas }}</h3>
    </div>
    <div class="cell medium-4 callout primary" style="text-align: center;">
      <h5>Total Anulaciones</h5>
      <h3>S/ {{ total_anulaciones }}</h3>
    </div>
    <div class="cell medium-4 callout alert" style="text-align: center;">
      <h5>Productos en 0</h5>
      <h3>{{ stok_cero }}</h3>
    </div>
  </div>

  <div class="cell">
    <h4 class="cell">Informe de Ingresas en la semana:</h4>
    <div class="cell">
      <table class="hover">
        <thead>
          <th>Fecha</th>
          <th>Numero Ventas</th>
          <th>Total Vendido</th>
          <th>Total Ganancias</th>
        </thead>
        <tbody>
          {% for venta in resumen_semana %}
            <tr>
              <td>{{ venta.sale__date_sale__date }}</td>
              <td>{{ venta.num_ventas }}</td>
              <td>{{ venta.total_vendido }}</td>
              <td>{{ venta.total_ganancias }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock panel-content %}

marketjs/market/templates/home/base_home.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

marketjs/market/templates/home/index.html
{% extends "home/base_home.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-container">
    <div class="grid-y medium-grid-frame align-center">
      <div class="grid-x grid-padding-x align-center">
        <div class="callout warning">
            <h5 class="cell" style="text-align: center;">Bienvenido al Sistema: {{user.full_name}}</h5>
        </div>
      </div>
    </div>
  </div>

{% endblock panel-content %}

marketjs/market/templates/home/reporte_admin.html
{% extends "home/base_home.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  
  {% include "includes/reporte-options.html" %}

  <div class="cell grid-x grid-margin-x" style="margin-top: 1em;">
    <h4 class="cell">Tus Ventas hasta hoy: <b style="font-size: 28px;">S/. {{ total_ventas }}</b></h4>
    <table class="hover">
      <thead>
        <th>Mes</th>
        <th>Num Ventas</th>
        <th>Venta Total</th>
        <th>Ganancia Total</th>
      </thead>
      <tbody>
        {% for venta in resumen_ventas_mes %}
        <tr>
          <td>{{ venta.sale__date_sale__date__month }} / {{venta.sale__date_sale__date__year}}</td>
          <td>{{ venta.cantidad_ventas }}</td>
          <td>S/. <b> {{ venta.total_ventas }} </b></td>
          <td>S/. <b style="color: #01579b;"> {{ venta.ganancia_total }} </b></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

{% endblock panel-content %}

marketjs/market/templates/home/reporte_liquidacion.html
{% extends "home/base_home.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  
  {% include "includes/reporte-options.html" %}

  <form class="cell grid-x grid-x-margin" method="GET">
    <div class="cell medium-3">
      <label>Proveedor:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{form.provider}}
      </div>
    </div>
    <div class="cell medium-3">
      <label>Fecha Inicio:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{form.date_start}}
      </div>
    </div>
    <div class="cell medium-3">
      <label>Fecha Fin:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{form.date_end}}
      </div>
    </div>
    <div class="cell medium-3">
      <label for="">Buscar</label>
      <button type="submit" class="cell medium-3 button">Buscar</button>
    </div>
    
  </form>

  <div class="cell grid-x grid-margin-x" style="margin-top: 1em;">
    <h4 class="cell">Total a Pagar: <b style="font-size: 28px;">S/. {{ total_ventas }}</b></h4>
    <table class="hover">
      <thead>
        <th>Fecha</th>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Precio Compra</th>
        <th>Total</th>
      </thead>
      <tbody>
        {% for venta in ventas_liquidacion %}
          <tr>
            <td>{{ venta.sale.date_sale }}</td>
            <td>{{ venta.product.name }}</td>
            <td>{{ venta.count }}</td>
            <td>{{ venta.price_purchase }}</td>
            <td>{{ venta.sub_total }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

{% endblock panel-content %}

marketjs/market/templates/home/resumen_ventas.html
{% extends "caja/base_caja.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x">
  {% include "includes/reporte-options.html" %}

  <form class="cell grid-x grid-x-margin" method="GET">
    <div class="cell medium-4">
      <label>Fecha Inicio:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{form.date_start}}
      </div>
    </div>
    <div class="cell medium-4">
      <label>Fecha Fin:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-calendar"></i></span>
        {{form.date_end}}
      </div>
    </div>
    <div class="cell medium-4">
      <label for="">Buscar</label>
      <button type="submit" class="cell medium-3 button">Buscar</button>
    </div>
    
  </form>

  <div class="cell" style="margin-top: 1em;">
    <h4 class="cell">Ventas en Rango de Fechas:</h4>
    <div class="cell">
      {% for venta in resumen_ventas %}
        <table>
          <thead style="border: 1px solid green;">
            <th>N° {{venta.id}}</th>
            <th>Fecha: {{venta.date_sale|date:'m/d/Y P' }}</th>
            <th>PAGO: {{venta.get_type_payment_display}}</th>
            <th>PAGO: {{ venta.get_type_invoce_display }}</th>
            <th>CANTIDAD: {{venta.count}}</th>
            <th>TOTAL: S/ {{ venta.amount }}</th>
          </thead>
        </table>
        <table class="hover">
          <thead>
            <th>Producto</th>
            <th>Precio Venta</th>
            <th>Cantidad</th>
            <th>Sub Total</th>
          </thead>
          <tbody>
            {% for detalle in venta.detail_sale.all %}
              <tr>
                <td>{{ detalle.product.name }}</td>
                <td>S/. {{ detalle.price_sale }}</td>
                <td>{{ detalle.count }}</td>
                <td>S/ {{ detalle.subtotal }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock panel-content %}