empleados/applications/departamento/urls.py
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(),
         name='departamento_list'),
    path('new-departamento/', views.newDepartamentoView.as_view(),
         name='nuevo_departamento')
]

empleados/applications/persona/urls.py
from django.urls import path

from . import views

app_name = 'persona_app'


urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-area/<shorname>/',
         views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('lista-empleados-admin/',
         views.ListEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('habilidades-empleado/', views.ListHabilidadesEmpleados.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(),
         name='empleado_detail'),
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado')
]

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app persona
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home
    re_path('', include('applications.home.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/applications/departamento/models.py
from django.db import models


class Departamento(models.Model):
    """ Modelo para tabla departamento """

    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField(
        'Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name')

    def __str__(self):
        return str(self.id) + ' | ' + self.name + ' | ' + self.shor_name

empleados/applications/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)

empleados/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic import (ListView)

from applications.persona.models import Empleado
from .models import Departamento

from .forms import NewDepartamentoForm


class DepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    model = Departamento
    context_object_name = 'departamentos'


class newDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shorname']
        )

        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='3',
            departamento=depa
        )

        return super(newDepartamentoView, self).form_valid(form)

empleados/templates/departamento/lista.html
<!-- Plantilla -->
{% extends 'base.html' %}

<!-- Titulo -->
{% block title %} Listado de departamentos {% endblock title %}

<!-- Contenido -->
{% block content %}

<!-- Header  -->
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Lista de Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>

                    {% for departamento in departamentos %}
                    <tr>
                        <td>{{ departamento.name }}</td>
                        <td>{{ departamento.shor_name }}</td>
                        <td>
                            <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

empleados/templates/departamento/new_departamento.html
<!-- Plantilla -->
{% extends 'base.html' %}

<!-- Titulo -->
{% block title %} Registrar Departamento {% endblock title %}

<!-- Contenido -->
{% block content %}

<!-- Header  -->
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h2 class="cell">
            Registrar Departamento
        </h2>
        <form class="cell callout grid-x grid-margin-x" method="post">
            {% csrf_token %}

            <h3 class="cell">Datos Empleados</h3>

            <div class="cell large-6 ">
                <label>Nombres:
                        {{ form.nombre }}
                    </label>
            </div>

            <div class="cell large-6 ">
                <label>Apellidos:
                        {{ form.apellidos }}
                    </label>
            </div>

            <h3 class="cell">Datos de Departamento</h3>

            <div class="cell large-6 ">
                <label>Departamento:
                        {{ form.departamento }}
                    </label>
            </div>

            <div class="cell large-6 ">
                <label>Nombre corto:
                        {{ form.shorname }}
                    </label>
            </div>

            <div class="cell">
                <button type="submit" class="primary button">Guardar</button>
            </div>
        </form>

    </div>
</div>
{% endblock content %}