usuariosdj/usuarios/apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
    path('panel/', views.HomePage.as_view(), name='panel'),
    path('mixin/', views.TemplatePruebaMixin.as_view(), name='mixin'),
]

usuariosdj/usuarios/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.Login.as_view(), name='user-login'),
    path('logout/', views.logoutView.as_view(), name='user-logout'),
    path('update-password/', views.UpdatePassword.as_view(), name='update-password'),
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(),
         name='user-verification'),
]

usuariosdj/usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('apps.users.urls')),
    re_path('', include('apps.home.urls')),
]

usuariosdj/usuarios/apps/home/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import (TemplateView)


class FechaMixin(object):
    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class HomePage(LoginRequiredMixin, FechaMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:user-login')


class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/mixin.html'

usuariosdj/usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel de usuario</title>
</head>

<body>

    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}}</h3>

    <ul>
        <li>Fecha actual: <strong>{{ fecha }}</strong> </li>
        <li><a href="{% url 'users_app:update-password' %}">Actualizar datos</a></li>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesión</a></li>
    </ul>

</body>

</html>

usuariosdj/usuarios/templates/home/mixin.html
<h1>mixin</h1>

{{ fecha }}